### ISSUE TITLE
Evaluate ways to monitor Superset and take decision on how to proceed

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/superset-operator#13]
We want monitoring for Superset.
@siegfriedweber did some initial research but we did not come to a final conclusion on how to integrate it and what to monitor.

I'd say that monitoring is important but for Superset simple monitoring is fine for the beginning. We need to be able to tell whether the service is green/yellow/red. Everything beyond that is nice-to-have.

This ticket is a research ticket and the outcome should be a way forward (i.e. new tickets) on how to integrate Superset with our existing Prometheus architecture.

Superset provides metrics via [StatsD](https://github.com/statsd/statsd). It must be evaluated if a StatsD to Prometheus metrics exporter, like [statsd_exporter](https://github.com/prometheus/statsd_exporter), is a reasonable solution.

**Comment by lfrancke** [comment]
Thank you! Sounds like a good plan then.

I can update the other ticket next week and move it to to-do.

**Comment by siegfriedweber** [comment]
Follow-up ticket: #95
