### ISSUE TITLE
Custom resources are not created

### ISSUE THREAD

**Issue by semjongeist** [stackabletech/superset-operator#139]
The yaml configuration for the custom resource doesn't seem to be interpreted correctly.

Superset-Operator-Version: 0.3.0 (stable-repo)
yaml, same as in examples for the 0.3.0 tag:
- apply works, but no instances are created of the CRD

Superset-Operator-Version: 0.4.0-nightly (devel-repo)
yaml, same as in main branch:
- syntax error, unknown field "statsdExporterVersion"
- without "statsdExporterVersion" the apply works, but also no instances are created of the CRD

In both cases, the secrets were also created (secret-operator: 0.2.0 and 0.4.0-nightly).
After it didn't work on the managed cluster, I also tried it on a local "K8s in Docker" but didn't succeed either.
I didn't see any errors in the operator logs either.

Did I forget something or did something wrong?

**Comment by semjongeist** [comment]
OK, it worked.
However, the pods still have errors:
```
logging was configured successfully
2022-03-01 17:08:59,101:INFO:superset.utils.logging_configurator:logging was configured successfully
2022-03-01 17:08:59,105:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
/usr/local/lib/python3.8/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
   warnings.warn(
2022-03-01 17:08:59,119:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) could not translate host name "superset-postgresql.default.svc.cluster.local" to address: name or service not known

(Background on this error at: http://sqlalche.me/e/13/e3q8)
Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
```
Do I still need a Postgres service to deploy?

**Comment by maltesander** [comment]
> OK, it worked. However, the pods still have errors:
> 
> ```
> logging was configured successfully
> 2022-03-01 17:08:59,101:INFO:superset.utils.logging_configurator:logging was configured successfully
> 2022-03-01 17:08:59,105:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
> /usr/local/lib/python3.8/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
>    warnings.warn(
> 2022-03-01 17:08:59,119:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) could not translate host name "superset-postgresql.default.svc.cluster.local" to address: name or service not known
> 
> (Background on this error at: http://sqlalche.me/e/13/e3q8)
> Loaded your LOCAL configuration at [/app/pythonpath/superset_config.py]
> ```
> 
> Do I still need a Postgres service to deploy?

Yes, you can check here https://github.com/stackabletech/superset-operator/blob/main/docs/modules/ROOT/pages/usage.adoc#database-for-the-superset-metadata

**Comment by semjongeist** [comment]
I went about it a bit naively and assumed that the database was already created by the operator (as in other tools).
Thanks again for the help :+1:
