### ISSUE TITLE
TrinoConnection missing (rob)

### ISSUE THREAD

**Issue by fhennig** [stackabletech/superset-operator#153]
From the CRD Review.

**Comment by sbernauer** [comment]
I think this is a duplicate of https://github.com/stackabletech/superset-operator/issues/3

**Comment by maltesander** [comment]
> I think this is a duplicate of #3

Yeah closing this!

**Comment by Spikebady** [comment]
It use to be clear.It is explicit video of my wife claiming to be a sleep.We are going through a court battle and I really need help proven that it exists
