### ISSUE TITLE
Druid connection is not established if Druid is started afterwards

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/superset-operator#174]
If the DruidConnection is applied before the Druid cluster is started then the DruidConnection remains in status "Pending". The reconciliation should also happen when the Druid cluster changes.

**Comment by fhennig** [comment]
It would be good if we had a test case for this bug.

The fix should be that the controller for the DruidConnection also watches the ConfigMap objects to be updated of new discovery config maps
