### ISSUE TITLE
Move tests to superset-operator and template them

### ISSUE THREAD

**Issue by adwk67** [stackabletech/superset-operator#195]
This issue covers:

- moving tests to the operator repo
- using templated tests
- providing a postgres DB as part of the test to avoid DB schema clashes

**Comment by fhennig** [comment]
Some tests have already been moved here: https://github.com/stackabletech/superset-operator/commit/9453b9b7b6e5d4088a844abf5b97f9e8102393cf

In the commit message it says "LDAP tests will follow", I think I'll leave this to @sbernauer since it seems like he had a plan on how to do this
