### ISSUE TITLE
[NEW VERSION] Superset 2.0.1, 2.1.0

### ISSUE THREAD

**Issue by fhennig** [stackabletech/superset-operator#237]
**Which new version of Apache Superset should we support?**

New major version 2.0

**Additional information**

See the [changelog](https://github.com/apache/superset/blob/master/CHANGELOG.md), the [release notes](https://github.com/apache/superset/tree/master/RELEASING/release-notes-2-0) and [breaking changes](https://github.com/apache/superset/blob/master/UPDATING.md#breaking-changes-1).

**Changes / Additions**

In the scope of this ticket:

- check that tests, getting started scripts, documentation and demos work with the new version. Many of the changes are UI-based, so screenshots should be checked for accuracy.
- have a look at the items below from the release notes and create new issues for things which merit further work
- as many changes are UI-based it may be worth showcasing some new UI features in our demos

2.0.1 is not released as of the time of this writing but the release vote is ongoing: https://lists.apache.org/thread/vjhnxw1yrd3wo356c0pgljv9nn7trmyv

From the release notes:-

- 2.0.0
  - resource limits (check these against our defaults?): [20052](https://github.com/apache/superset/pull/20052)
  - switch from sqlalchemy-trino to trino-python-client: [19957](https://github.com/apache/superset/pull/19957)
  - min. python version is now 3.8: [19017](https://github.com/apache/superset/pull/19017)
 - 1.5.2
   - (only minor fixes)

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

## TODO

- [x] https://github.com/stackabletech/docker-images/pull/216
- [x] https://github.com/stackabletech/superset-operator/pull/362

**Comment by maltesander** [comment]
Do we already want to do this or wait for a 2.0 patch release @lfrancke ?

**Comment by lfrancke** [comment]
Good question: @siegfriedweber @fhennig @soenkeliebau 
Any opinions? Usually I'd prefer for us to not jump on a new major version immediately but if you think it's worth it I'm happy to...

**Comment by adwk67** [comment]
I think it makes sense doing a refinement on this, if only to list the main changes up to 2.0.0. We can always put it back in the "waiting for" column if we decide to wait for 2.x.

**Comment by lfrancke** [comment]
The new vote has received another -1 which might fail the release.
I don't feel too confident about supporting Superset 2.0 right now.
I will remove it from this release and we can try again next release.

**Comment by sbernauer** [comment]
Ok for me

**Comment by sbernauer** [comment]
New vote started https://lists.apache.org/thread/jrl1cs4wnl22mtyz926tllr8k513gx9x

**Comment by lfrancke** [comment]
No, that is the result of the new vote and it failed again :)

**Comment by sbernauer** [comment]
Ah sry :facepalm:

**Comment by sbernauer** [comment]
They finally did it...

**Comment by soenkeliebau** [comment]
Needs input from @lfrancke on whether both versions should be released or just 2.1.0

**Comment by lfrancke** [comment]
I think only 2.1.0 is required.
Any other opinions?
