### ISSUE TITLE
Difficulty using superset operator on AKS

### ISSUE THREAD

**Issue by StefanLueders** [stackabletech/superset-operator#347]
### Affected version

23.1.0

### Current and expected behavior

I am trying to use the superset operator in a simple (fresh) AKS cluster. I followed the Installation and Getting Started instruction in the matching section of the docs. Unfortunately it does not work.

Here is the state of the cluster after I allowed it to settle (`kubectl get all`):

```NAME                                                READY   STATUS      RESTARTS   AGE
pod/commons-operator-deployment-5448b5b778-mv8vq    1/1     Running     0          15m
pod/secret-operator-daemonset-cpgdj                 3/3     Running     0          15m
pod/simple-superset-node-default-0                  2/2     Running     0          5m17s
pod/simple-superset-z7qww                           0/1     Error       0          13m
pod/simple-superset-zcj28                           0/1     Completed   0          7m52s
pod/superset-operator-deployment-5794986db4-cszlg   1/1     Running     0          15m
pod/superset-postgresql-0                           1/1     Running     0          14m

NAME                                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/kubernetes                     ClusterIP   10.0.0.1       <none>        443/TCP             19m
service/simple-superset-external       NodePort    10.0.251.166   <none>        8088:31733/TCP      5m50s
service/simple-superset-node-default   ClusterIP   None           <none>        8088/TCP,9102/TCP   5m50s
service/superset-postgresql            ClusterIP   10.0.14.207    <none>        5432/TCP            14m
service/superset-postgresql-hl         ClusterIP   None           <none>        5432/TCP            14m

NAME                                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/secret-operator-daemonset   1         1         1       1            1           <none>          15m

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/commons-operator-deployment    1/1     1            1           15m
deployment.apps/superset-operator-deployment   1/1     1            1           15m

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/commons-operator-deployment-5448b5b778    1         1         1       15m
replicaset.apps/superset-operator-deployment-5794986db4   1         1         1       15m

NAME                                            READY   AGE
statefulset.apps/simple-superset-node-default   1/1     5m50s
statefulset.apps/superset-postgresql            1/1     14m

NAME                        COMPLETIONS   DURATION   AGE
job.batch/simple-superset   1/1           7m51s      13m
```

It appears there is some kind of connection issue between the components. The exact issues appears to not be consistent (I have seen slightly different outputs in the logs of the operator pod). Unfortunately I only have the latest log outputs (attached).

When I tried setting up a local cluster using kind everything worked fine.
[ss_job.log](https://github.com/stackabletech/superset-operator/files/11121981/ss_job.log)
[ss_node_default.log](https://github.com/stackabletech/superset-operator/files/11121982/ss_node_default.log)
[ss_operator.log](https://github.com/stackabletech/superset-operator/files/11121983/ss_operator.log)
[ss_z7qww.log](https://github.com/stackabletech/superset-operator/files/11121984/ss_z7qww.log)
[ss_zcj28.log](https://github.com/stackabletech/superset-operator/files/11121985/ss_zcj28.log)

### Environment

AKS, Basic Dev/Test configuration, 1-2 Nodes

### Would you like to work on fixing this bug?

no

**Comment by soenkeliebau** [comment]
Hi @StefanLueders ,

are you having any issues with the environment after it settles, or are you able to connect normally and use Superset?

The failed pod `pod/simple-superset-z7qww` doesn't necessarily mean that anything went wrong. This is the job initializing the Superset database and if that tries connecting to the database before the db is ready to accept connections it'll fail.
It does retry until it succeeds though, as you can see in the line below where `pod/simple-superset-zcj28` succeeded.

In principle this looks like a successful deployment to me :)

**Comment by StefanLueders** [comment]
I just tried and I was, in fact, able to connect. I was definitely not able to connect earlier, but I have since torn down and set up the system. I guess it is related to the fact that the error changed, and I did not try connecting again since there were still errors.

Previously, there was some issue reconciling objects - it kept trying and kept failing. The Database never went up.

At least it works now, I guess. Thanks.

**Comment by StefanLueders** [comment]
I am getting the original issue again. My superset operator keeps logging the following two lines:

```
2023-04-03T06:51:37.225321Z  INFO reconciling object{object.ref=SupersetCluster.v1alpha1.superset.stackable.tech/simple-superset.default object.reason=error policy requested retry}: stackable_superset_operator::superset_controller: Starting reconcile
2023-04-03T06:51:37.273365Z ERROR stackable_operator::logging::controller: Failed to reconcile object controller.name="supersetcluster.superset.stackable.tech" error=reconciler for object SupersetCluster.v1alpha1.superset.stackable.tech/simple-superset.default failed error.sources=[superset db SupersetDB.v1alpha1.superset.stackable.tech/simple-superset.default initialization failed, not starting superset]
```

**Comment by StefanLueders** [comment]
It seems to be working right now - at some point in the last few hours it fixed itself. I will try that next time I run into the issue.

**Comment by lfrancke** [comment]
We'll close this in favor of the ticket Sebastian created https://github.com/stackabletech/superset-operator/issues/351

But feel free to reopen if you think this is a separate thing!
