### ISSUE TITLE
Investigate compatibility with ActiveDirectory

### ISSUE THREAD

**Issue by razvan** [stackabletech/superset-operator#363]
# Description

 See report here: https://github.com/orgs/stackabletech/discussions/17

# Notes

* Flask/Python-LDAP configuration [differs](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-ldap) slightly between OpenLDAP and Active Directory.
  * _Answer: it seems the exact settings listed there make no difference._ 
* Logging configuration doesn't seem to have any effect on `python-ldap`.

**Comment by razvan** [comment]
The customer problem is solved and was caused by a faulty ldap search filter.

Two follow up issues created:
* https://github.com/stackabletech/issues/issues/382
* https://github.com/stackabletech/superset-operator/issues/365

**Comment by lfrancke** [comment]
You mentioned that our defaults are more geared for OpenLDAP rather than Active Directory.
Is that true?

And is there anything in the docs we can do better to document AD usage?

**Comment by razvan** [comment]
To the first question: yes. We set `AUTH_LDAP_UID_FIELD=uid` which is not what AD uses by default apparently.

I would update the docs  as part of https://github.com/stackabletech/issues/issues/382

**Comment by lfrancke** [comment]
Sorry, old issue: So, you'd say we can close this?

**Comment by razvan** [comment]
yes
