### ISSUE TITLE
Document how users can load examples

### ISSUE THREAD

**Issue by dervoeti** [stackabletech/superset-operator#397]
As a user, I would like to have an easy way to load the examples Superset provides to get a rough impression of the product.

Up until now, this was supported via the `.spec.clusterConfig.loadExamplesOnInit` option, but this option is dropped now to simplify the upgrading process of Superset (see https://github.com/stackabletech/superset-operator/issues/351 and https://github.com/stackabletech/superset-operator/pull/396).

So we need to document an alternative way for the user on how to load the examples instead. I can think of at least two options to solve this:
 - Provide a `kubectl apply` command that creates a `Job` that runs `superset load-examples`. This `Job` has to use the same image as the Superset Pods.
 - Provide a command that runs the `superset load-examples` command in one of the running Superset Pods (`kubectl exec ...`)

This has to be in place once the `.spec.clusterConfig.loadExamplesOnInit` option is removed from the CRD.

**Comment by fhennig** [comment]
We decided to do it with a Job, because the loading of the examples has different resource requirements than the superset Pod.
