### ISSUE TITLE
Connect Superset to Druid

### ISSUE THREAD

**Issue by stefanigel** [stackabletech/superset-operator#4]
**Acceptance Criteria**
- [ ]  Superset can connect to a Druid instance managed by Stackable

**Comment by fhennig** [comment]
Alright, so I just checked and this is already possible! Following [the documentation](https://superset.apache.org/docs/databases/druid):
1. Have a running druid and a running superset instance
2. In superset got to the `Add Database` form
3. Select to connect to `Apache Druid`
4. Enter the connect string: `druid://simple-router-default:8888/druid/v2/sql`
5. Done!

But I imagine that we'd want to use discovery. So we'd have a CR somewhere that is read by the superset-operator where we specify which druid cluster to connect to and then the operator configures the superset instance to connect to the druid cluster. This also requires discovery for Druid.

**Comment by fhennig** [comment]
Alright, druid discovery is on the way.

For setting up the connection in superset programmatically, I found this nifty feature tucked away in the documentation under "miscellaneous": https://superset.apache.org/docs/miscellaneous/importing-exporting-datasources Importing and exporting datasources from/to yaml files!  We can use an import from a file inside the init container probably to set it up.

**Comment by fhennig** [comment]
Done
https://github.com/stackabletech/superset-operator/pull/71
