### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by fhennig** [stackabletech/superset-operator#405]
Out-of-the-box, Superset does not have OpenID Connect (OIDC) support. It does however support OAuth 2.0, and OIDC providers like Keycloak provide OAuth 2.0 support as well, so Superset can be configured to work with that.

Direct support for OIDC would require adding an addtional dependency to the Docker image and modifying some code. the code changes would also be on a security-critical path and we would need to be aware of upstream modifications each update. It would be a difficult route to go down I believe.

[useful Stackoverflow question](https://stackoverflow.com/questions/47678321/using-openid-keycloak-with-superset) - [our docs on the topic](https://docs.stackable.tech/home/stable/superset/usage-guide/security#_openid_connect)

**Comment by lfrancke** [comment]
Does this contain a CRD change? If so: Is it breaking?

**Comment by siegfriedweber** [comment]
@lfrancke Yes, there is a CRD change. An `oidc` property was added to the authentication entries, which is only required if an OIDC AuthenticationClass is provided, see https://docs.stackable.tech/home/nightly/contributor/adr/adr032-oidc-support#_product_cluster_configuration_design. So this change is not breaking.
