### ISSUE TITLE
[NEW VERSION] Superset 2.1.1

### ISSUE THREAD

**Issue by fhennig** [stackabletech/superset-operator#408]
**Which new version of Apache Superset should we support?**

2.1.1

**Additional information**

changelog: https://github.com/apache/superset/blob/master/CHANGELOG.md#211-sun-apr-23-154421-2023-0100

**Changes required**

nothing, just fixes

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [ ] Update the Docker image
- [ ] Update documentation to include supported version(s)
- [ ] Update and test getting started guide with updated version(s)
- [ ] Update operator to support the new version (if needed)
- [ ] Update integration tests to test use the new versions (in addition or replacing old versions
- [ ] Update examples to use new versions

**Comment by maltesander** [comment]
Done in 23.11.
