### ISSUE TITLE
[NEW VERSION] Superset 3.0.0

### ISSUE THREAD

**Issue by fhennig** [stackabletech/superset-operator#409]
**Which new version of Apache Superset should we support?**

3.0.0

**Additional information**

changelog: https://github.com/apache/superset/blob/master/CHANGELOG.md#300-thu-aug-24-133627-2023--0600

**Changes required**

Are there any upstream changes that we need to support?
e.g. new features, changed features, deprecated features etc.

python 3.9 support

lots of small new features and fixes

**Implementation checklist**

Please don't change anything in this list.
Not all of these steps are necessary for all versions.

- [ ] Update the Docker image
- [ ] Update documentation to include supported version(s)
- [ ] Update and test getting started guide with updated version(s)
- [ ] Update operator to support the new version (if needed)
- [ ] Update integration tests to test use the new versions (in addition or replacing old versions
- [ ] Update examples to use new versions

**Comment by maltesander** [comment]
We currently have 3.0.1.
