### ISSUE TITLE
Document requirement for the operator to communicate with its deployed clusters / postgres for Druid-(possible Trino-) connections

### ISSUE THREAD

**Issue by maltesander** [stackabletech/superset-operator#445]
The superset operator must be able to communicate with its deployed clusters / postgres etc. in order to create a connection to e.g. Druid and other products (possible Trino in the future).

We should document that this is the case and how to e.g. enable this in a restricted environments via e.g. network policies.

**Comment by fhennig** [comment]
documenting the NetworkPolicy will be part of this ticket: https://github.com/stackabletech/issues/issues/449
