### ISSUE TITLE
Support LDAP authentication

### ISSUE THREAD

**Issue by stefanigel** [stackabletech/superset-operator#5]
As a user I'd like to use my existing LDAP/AD credentials to log into Superset.

This depends on the reference architecture developed in https://github.com/stackabletech/issues/issues/170

**Comment by sbernauer** [comment]
Spike finished.
https://github.com/stackabletech/superset-operator/pull/145 for the Implementation
https://github.com/stackabletech/integration-tests/pull/175 for integration test
